Name:           ros-hydro-lcas-hri
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS lcas_hri package

Group:          Development/Libraries
License:        MIT
URL:            https://github.com/LCAS/ros_systems
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       mongodb
Requires:       ros-hydro-mongodb-log
Requires:       ros-hydro-mongodb-store
Requires:       ros-hydro-mongodb-store-msgs
Requires:       ros-hydro-scitos-cmd-vel-mux
Requires:       ros-hydro-scitos-common
Requires:       ros-hydro-scitos-description
Requires:       ros-hydro-scitos-docking
Requires:       ros-hydro-scitos-drivers
Requires:       ros-hydro-scitos-msgs
Requires:       ros-hydro-scitos-ptu
Requires:       ros-hydro-scitos-teleop
Requires:       ros-hydro-strands-morse
Requires:       ros-hydro-strands-perception-people
BuildRequires:  ros-hydro-catkin

%description
The lcas_hri metapackage

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Oct 22 2014 Christian Dondrup <cdondrup@lincoln.ac.uk> - 0.0.2-0
- Autogenerated by Bloom

